---
- name: Submariner prerequisites
  hosts: localhost
  gather_facts: false
  vars:
    primary_cluster: "{{ lookup('env', 'PRIMARY_CLUSTER') | default('ocp-primary', true) }}"
    secondary_cluster: "{{ lookup('env', 'SECONDARY_CLUSTER') | default('ocp-secondary', true) }}"
    submariner_broker_namespace: "{{ lookup('env', 'SUBMARINER_BROKER_NAMESPACE') | default('resilient-broker', true) }}"
  roles:
    - submariner_prerequisites
