---
apiVersion: v1
kind: ConfigMap
metadata:
  name: regionaldr-ansible
  namespace: open-cluster-management
  labels:
    app.kubernetes.io/name: regionaldr-ansible
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
data:
{{ include "rdr.regionaldrAnsibleConfigMapData" . }}
{{- if eq "1" (include "rdr.odfPostInstallFixesEnabled" . | trim) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: regionaldr-ansible
  namespace: {{ include "rdr.clusterCaMgtNamespace" . }}
  labels:
    app.kubernetes.io/name: regionaldr-ansible
    app.kubernetes.io/component: ca-workloads
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
data:
{{ include "rdr.regionaldrAnsibleConfigMapData" . }}
{{- end }}
