{{- $drpc := .Values.drpc | default dict }}
{{- $kop := index $drpc "kubeObjectProtection" | default dict }}
{{- $kos := index $kop "kubeObjectSelector" | default dict }}
{{- $pvcSel := index $drpc "pvcSelector" | default dict }}
---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  annotations:
    drplacementcontrol.ramendr.openshift.io/app-namespace: {{ $drpc.namespace | default "openshift-dr-ops" }}
    argocd.argoproj.io/sync-wave: "10"
  labels:
    cluster.open-cluster-management.io/backup: ramen
  name: {{ $drpc.name | default "gitops-vm-protection" }}
  namespace: {{ $drpc.namespace | default "openshift-dr-ops" }}
spec:
  drPolicyRef:
    apiVersion: ramendr.openshift.io/v1alpha1
    kind: DRPolicy
    name: {{ index $drpc "drPolicyRef" "name" | default "2m-vm" }}
  kubeObjectProtection:
    captureInterval: {{ index $kop "captureInterval" | default "2m0s" }}
{{- if empty $kos }}
    kubeObjectSelector: {}
{{- else }}
    kubeObjectSelector:
{{- toYaml $kos | nindent 6 }}
{{- end }}
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: {{ index $drpc "placementRef" "name" | default "gitops-vm-protection-placement-1" }}
    namespace: {{ index $drpc "placementRef" "namespace" | default "openshift-dr-ops" }}
  preferredCluster: {{ include "rdr.preferredClusterName" . }}
  protectedNamespaces:
  {{- with index $drpc "protectedNamespaces" }}
  {{- toYaml . | nindent 2 }}
  {{- else }}
  - gitops-vms
  {{- end }}
{{- if empty $pvcSel }}
  pvcSelector: {}
{{- else }}
  pvcSelector:
{{- toYaml $pvcSel | nindent 4 }}
{{- end }}
