apiVersion: batch/v1
kind: Job
metadata:
  name: submariner-sg-tagger
  namespace: open-cluster-management
  labels:
    app.kubernetes.io/name: submariner-sg-tag
    app.kubernetes.io/component: aws-tagging
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 3600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: sg-tagger
        image: {{ $.Values.ansible.containerImage }}
        env:
        - name: AWS_SDK_LOAD_CONFIG
          value: "false"
        - name: AWS_EC2_METADATA_DISABLED
          value: "true"
        command:
        - /bin/bash
        - -c
        - |
{{ include "rdr.ansibleBootstrap" . | indent 10 }}
            ansible-playbook -i inventory/hosts playbooks/submariner_sg_tag.yml
        volumeMounts:
        - name: ansible
          mountPath: /ansible-cm
          readOnly: true
      volumes:
      - name: ansible
        configMap:
          name: regionaldr-ansible
      serviceAccountName: submariner-sg-tagger
