{{- if .Values.clusterCaMgt.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "rdr.clusterCaMgtNamespace" . }}
  labels:
    app.kubernetes.io/name: regionaldr-with-virt-chart
    app.kubernetes.io/component: ca-workloads
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
